services:
  web:
    build: .
    command: ["./run_web.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
   
  redis:
   image: redis:6.2-alpine
   ports:
     - "6379:6379"

  redis-commander:
   container_name: redis_commander
   image: rediscommander/redis-commander:latest
   environment:
     - REDIS_HOSTS=local:redis:6379
   ports:
     - "8082:8081"