# Generated by Django 4.0.5 on 2022-07-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_user',
            options={},
        ),
        migrations.AlterField(
            model_name='login_user',
            name='token',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterModelTable(
            name='login_user',
            table=None,
        ),
    ]
