# Generated by Django 4.0.5 on 2022-07-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0002_alter_login_user_options_alter_login_user_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_user',
        ),
    ]
