# Generated by Django 4.0.5 on 2022-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
