# Generated by Django 4.0.5 on 2022-07-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0006_tokenmodel_delete_loginuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenmodel',
            old_name='access_token',
            new_name='access',
        ),
        migrations.RenameField(
            model_name='tokenmodel',
            old_name='refresh_token',
            new_name='refresh',
        ),
    ]
