# Generated by Django 4.0.5 on 2022-07-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0007_rename_access_token_tokenmodel_access_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenModel',
            new_name='LoginUserModel',
        ),
    ]
